### ISSUE TITLE
Cost CSV Export shows possible errors or warnings in first rows

### ISSUE THREAD

**Issue by sttomm** [meshcloud/collie-cli#54]
When some error occur when doing a csv export of the tenant costs, the CSV headers are not set correctly, because warnings like "no management group selected for azure" or" gcp is not supported" are shown in the first rows and used as headers. Those warnings should be shown as console output instead and shouldn't be part of the CSV export.

![image](https://user-images.githubusercontent.com/32126381/124711850-da45d080-defe-11eb-9a67-4fac26d98159.png)

**Comment by Jelledb** [comment]
@sttomm 
It seems that the Deno detection of whether you're running in `tty` is not being detected properly.

Could you for debugging please install Deno (`brew install deno`) and run the following command:

`deno eval "console.log(Deno.isatty(Deno.stdout.rid))" > test.txt` and see what the content of the file contains. For me, it contains `false` which is the expected behavior.

**Comment by sttomm** [comment]
I executed it and also got `false`:

![image](https://user-images.githubusercontent.com/32126381/124758686-1c870600-df2f-11eb-878a-be3a8a0ff27f.png)

Getting the CSV export also works for me when the results are inc ache. But after i cleared the cache, the 2 log lines are present again in the csv file. SO this issue only appears if the cache is empty.
