### ISSUE TITLE
Remove blue color of `INFO` log statements

### ISSUE THREAD

**Issue by Jelledb** [meshcloud/collie-cli#92]
**Is your feature request related to a problem? Please describe.**
We should remove the blue color of log statements of level `INFO`. They look unreadable in a PowerShell console

**Reach of the feature request**
Windows users making use of PowerShell with the 

**Impact of the feature request**
log.info() statements are not visible.

**How would a solution look like?**
Either change the color to something less used as a background (purple?) or just remove the color altogether.

(optional) **Implementation Hints**
https://github.com/denoland/deno_std/issues/1077 -> Changing the color is currently not possible

**Comment by tfelix** [comment]
Yeah played around and its not easy. Maybe its worth considering if we actually need a logging framework after all? Its a bit awkward in the end anyways and I don't see much use after all to define different loglevels. Maybe we should just go with a plain old console.log (which we are using at a lot of places anyways because we just want vanilla text output without fancy formatting). With this we are more free for color control.

**Comment by Jelledb** [comment]
> Yeah played around and its not easy. Maybe its worth considering if we actually need a logging framework after all? Its a bit awkward in the end anyways and I don't see much use after all to define different loglevels. Maybe we should just go with a plain old console.log (which we are using at a lot of places anyways because we just want vanilla text output without fancy formatting). With this we are more free for color control.

Good point. But I guess we need it for separating between DEBUG and INFO+ statements and using the `--debug` flag for running.

**Comment by tfelix** [comment]
Yeah the debug thingy is a bit cumbersome. We could overwrite/hook into the actual log.debug() call and handle the debug log there though.
